// Code generated by Kitex v0.5.0. DO NOT EDIT.

package gptservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	api "github.com/icando/chatgpt-proxy-server/kitex_gen/api"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Echo(ctx context.Context, req *api.Request, callOptions ...callopt.Option) (r *api.Response, err error)
	CreateChatCompletion35(ctx context.Context, request *api.ChatCompletionRequest, callOptions ...callopt.Option) (r *api.ChatCompletionResponse, err error)
	CreateImage(ctx context.Context, request *api.ImageRequest, callOptions ...callopt.Option) (r *api.ImageResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kGPTServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kGPTServiceClient struct {
	*kClient
}

func (p *kGPTServiceClient) Echo(ctx context.Context, req *api.Request, callOptions ...callopt.Option) (r *api.Response, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Echo(ctx, req)
}

func (p *kGPTServiceClient) CreateChatCompletion35(ctx context.Context, request *api.ChatCompletionRequest, callOptions ...callopt.Option) (r *api.ChatCompletionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateChatCompletion35(ctx, request)
}

func (p *kGPTServiceClient) CreateImage(ctx context.Context, request *api.ImageRequest, callOptions ...callopt.Option) (r *api.ImageResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateImage(ctx, request)
}
