// Code generated by Kitex v0.5.0. DO NOT EDIT.

package gptservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	api "github.com/icando/chatgpt-proxy-server/kitex_gen/api"
)

func serviceInfo() *kitex.ServiceInfo {
	return gPTServiceServiceInfo
}

var gPTServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "GPTService"
	handlerType := (*api.GPTService)(nil)
	methods := map[string]kitex.MethodInfo{
		"CreateImage": kitex.NewMethodInfo(createImageHandler, newGPTServiceCreateImageArgs, newGPTServiceCreateImageResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.5.0",
		Extra:           extra,
	}
	return svcInfo
}

func createImageHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.GPTServiceCreateImageArgs)
	realResult := result.(*api.GPTServiceCreateImageResult)
	success, err := handler.(api.GPTService).CreateImage(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newGPTServiceCreateImageArgs() interface{} {
	return api.NewGPTServiceCreateImageArgs()
}

func newGPTServiceCreateImageResult() interface{} {
	return api.NewGPTServiceCreateImageResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateImage(ctx context.Context, request *api.ImageRequest) (r *api.ImageResponse, err error) {
	var _args api.GPTServiceCreateImageArgs
	_args.Request = request
	var _result api.GPTServiceCreateImageResult
	if err = p.c.Call(ctx, "CreateImage", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
