// Code generated by Kitex v0.5.0. DO NOT EDIT.
package gptservice

import (
	server "github.com/cloudwego/kitex/server"
	api "github.com/icando/chatgpt-proxy-server/kitex_gen/api"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler api.GPTService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
